# Generated by Django 3.1.2 on 2020-10-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_delete_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('ingredient_1', models.CharField(max_length=70)),
                ('ingredient_2', models.CharField(blank=True, max_length=70, null=True)),
                ('ingredient_3', models.CharField(blank=True, max_length=70, null=True)),
                ('ingredient_4', models.CharField(blank=True, max_length=70, null=True)),
                ('ingredient_5', models.CharField(blank=True, max_length=70, null=True)),
                ('ingredient_6', models.CharField(blank=True, max_length=70, null=True)),
                ('ingredient_7', models.CharField(blank=True, max_length=70, null=True)),
                ('method', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
