# Generated by Django 3.1.2 on 2020-10-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='product_measure',
            field=models.CharField(default='2 oz', max_length=50),
            preserve_default=False,
        ),
    ]
