# Generated by Django 3.1.2 on 2020-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_remove_cocktail_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_2',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_3',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_4',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_5',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_6',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_7',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
