# Generated by Django 3.1.2 on 2020-10-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20201031_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ['id']},
        ),
    ]
