# Generated by Django 3.1.2 on 2020-10-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
