# Generated by Django 3.1.2 on 2020-10-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201023_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_contents',
            field=models.TextField(default=''),
        ),
    ]
