# Generated by Django 3.1.2 on 2020-10-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proof',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
