# Generated by Django 3.1.2 on 2020-10-17 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201017_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
