# Generated by Django 3.1.2 on 2020-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreviews_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='authorised',
            field=models.BooleanField(default=False),
        ),
    ]
