# Generated by Django 3.1.2 on 2020-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201017_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
